name: PDFs from LaTeX
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get current date/time
        id: date
        run: echo "::set-output name=date::$(date +'%Y_%m_%d-%H_%M_%S')"
      - name: Compile LaTeX document (thesis)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - name: Compile LaTeX document (slides)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: slides.tex
      - name: Copy-rename PDFs
        run: |
          cp thesis.pdf EmanueleBallarin_MScThesis_CARSO_${{ steps.date.outputs.date }}.pdf
          mv thesis.pdf EmanueleBallarin_MScThesis_CARSO_latest.pdf
          cp slides.pdf EmanueleBallarin_MScThesisSlides_CARSO_${{ steps.date.outputs.date }}.pdf
          mv slides.pdf EmanueleBallarin_MScThesisSlides_CARSO_latest.pdf
      - name: Upload PDF as artifact (thesis, versioned)
        uses: actions/upload-artifact@v3
        with:
          name: EmanueleBallarin_MScThesis_CARSO_${{ steps.date.outputs.date }}
          path: EmanueleBallarin_MScThesis_CARSO_${{ steps.date.outputs.date }}.pdf
      - name: Upload PDF as artifact (slides, versioned)
        uses: actions/upload-artifact@v3
        with:
          name: EmanueleBallarin_MScThesisSlides_CARSO_${{ steps.date.outputs.date }}
          path: EmanueleBallarin_MScThesisSlides_CARSO_${{ steps.date.outputs.date }}.pdf
      - name: Upload PDF as artifact (thesis, unversioned, latest)
        uses: actions/upload-artifact@v3
        with:
          name: EmanueleBallarin_MScThesis_CARSO_latest
          path: EmanueleBallarin_MScThesis_CARSO_latest.pdf
      - name: Upload PDF as artifact (slides, unversioned, latest)
        uses: actions/upload-artifact@v3
        with:
          name: EmanueleBallarin_MScThesisSlides_CARSO_latest
          path: EmanueleBallarin_MScThesisSlides_CARSO_latest.pdf
